### ISSUE TITLE
NOAAPort GOES-17 Mesoscale Sectors not working

### ISSUE THREAD

**Issue by NaderCHASER** [Unidata/awips2-goesr#13]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
18.2.1-3
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
CentOS 7
* a description of the issue with the steps needed to reproduce it
GOES-17 Mesoscale sectors do not appear when ingesting from NOAAPort.

**Comment by tiffanycmeyer13** [comment]
In your EDEX logs are you given any information? 

Are you getting a warning like this in edex-ingest-unrecognized-files-20220107.log:

`WARN  2022-01-07 17:04:14,395 0184 [external.dropbox-4] RouteFailedLog: TIUR15 KNES 071657 PAA`

If so, edit your goesr.xml distribution file:

`vi /awips2/edex/data/utility/common_static/base/distribution/goesr.xml`

In the first regex, add a U:

`    <regex>^TI[SRU]</regex>`

Then save and close the file. 

You shouldn't have to restart EDEX, just wait until the top of the minute, and that distribution file will be reloaded and products should start ingesting.

**Comment by NaderCHASER** [comment]
This issue was created to track what the PR was resolving.
